/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.interfaz;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.awt.Frame;

/**
 *
 * @author poker
 */
public class DialogCrearFactura extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogCrearFactura.class.getName());

    /**
     * Creates new form DialogCrearFactura
     */
    public DialogCrearFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // 1. Aplicar los estilos visuales personalizados
        configurarEstilos();

        // 2. Ajustar tamaño automáticamente al contenido según los márgenes
        pack();

        // 3. Centrar
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelFormulario = new javax.swing.JPanel();
        lblClient = new javax.swing.JLabel();
        txtClient = new javax.swing.JTextField();
        btnSearchClient = new javax.swing.JButton();
        lblInvoiceType = new javax.swing.JLabel();
        jComboBoxInvoiceType = new javax.swing.JComboBox<>();
        panelBotones = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        btnCancel = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0));
        btnAccept = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Factura");
        setModal(true);
        setResizable(false);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 20, 10));
        panelFormulario.setLayout(new java.awt.GridBagLayout());

        lblClient.setText("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 15);
        panelFormulario.add(lblClient, gridBagConstraints);

        txtClient.setBackground(new java.awt.Color(153, 153, 153));
        txtClient.setEnabled(false);
        txtClient.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 10);
        panelFormulario.add(txtClient, gridBagConstraints);

        btnSearchClient.setPreferredSize(new java.awt.Dimension(40, 40));
        btnSearchClient.addActionListener(this::btnSearchClientActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        panelFormulario.add(btnSearchClient, gridBagConstraints);

        lblInvoiceType.setText("Tipo Factura");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 15);
        panelFormulario.add(lblInvoiceType, gridBagConstraints);

        jComboBoxInvoiceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completa", "Rectificativa" }));
        jComboBoxInvoiceType.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 1.0;
        panelFormulario.add(jComboBoxInvoiceType, gridBagConstraints);

        panelPrincipal.add(panelFormulario, java.awt.BorderLayout.CENTER);

        panelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 0, 10, 0));
        panelBotones.setLayout(new javax.swing.BoxLayout(panelBotones, javax.swing.BoxLayout.LINE_AXIS));
        panelBotones.add(filler1);

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        panelBotones.add(btnCancel);
        panelBotones.add(filler2);

        btnAccept.setText("Aceptar");
        btnAccept.addActionListener(this::btnAcceptActionPerformed);
        panelBotones.add(btnAccept);
        panelBotones.add(filler3);

        panelPrincipal.add(panelBotones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // 1. RECOGER DATOS
        String cliente = txtClient.getText();
        String tipoFactura = (String) jComboBoxInvoiceType.getSelectedItem();

        // Validación básica
        if (cliente.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente.");
            return;
        }

        // 2. CERRAR EL DIÁLOGO
        this.dispose();

        // 3. ENVIAR DATOS A LA VENTANA PRINCIPAL
        java.awt.Window padre = this.getOwner(); // Obtenemos la ventana de atrás

        // ¡OJO! Cambia 'Dashboard' por el nombre de tu clase principal (ej: Principal, MainFrame...)
        if (padre instanceof Principal) {
            Principal principal = (Principal) padre;

            // Llamamos al método puente que creamos en el Paso 2
            principal.abrirNuevaFactura(cliente, tipoFactura);
        }

    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnSearchClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClientActionPerformed
        // 1. Obtener ventana padre
        java.awt.Window parent = javax.swing.SwingUtilities.getWindowAncestor(this);

        // 2. Abrir el buscador
        DialogBuscarCliente buscador = new DialogBuscarCliente((Frame) parent, true);
        buscador.setVisible(true); // Se detiene aquí esperando

        // 3. Recuperar resultado
        String resultado = buscador.getClienteSeleccionado();

        // 4. Si hay resultado, ponerlo en el campo
        if (resultado != null) {
            txtClient.setText(resultado);
        }    }//GEN-LAST:event_btnSearchClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogCrearFactura dialog = new DialogCrearFactura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearchClient;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JComboBox<String> jComboBoxInvoiceType;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblInvoiceType;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtClient;
    // End of variables declaration//GEN-END:variables

    private void configurarEstilos() {
        // --- 1. FONDO VERDE MENTA ---
        panelPrincipal.setBackground(Estilos.COLOR_VERDE_FUERTE);

        // TRANSPARENCIA: Hacemos transparentes los paneles que pusiste encima
        // para que se vea el verde del panelPrincipal
        panelFormulario.setOpaque(false);
        panelBotones.setOpaque(false);

        // --- 2. CAMPO CLIENTE (DESACTIVADO) ---
        txtClient.setBackground(Color.LIGHT_GRAY);
        txtClient.setForeground(Estilos.COLOR_NEGRO_PURO);
        txtClient.setFont(Estilos.FUENTE_BOTON);

        // Borde redondeado
        txtClient.putClientProperty(com.formdev.flatlaf.FlatClientProperties.STYLE, ""
                + "arc: 10; borderWidth: 1; borderColor: #aaaaaa; "
                + "margin: 0,10,0,10; focusWidth: 2; focusedBorderColor: #FFFFFF;");

        // --- 3. ETIQUETAS ---
        java.awt.Font fuenteBold = Estilos.FUENTE_BOTON;
        lblClient.setFont(fuenteBold);
        lblClient.setForeground(Estilos.COLOR_NEGRO_PURO);
        lblInvoiceType.setFont(fuenteBold);
        lblInvoiceType.setForeground(Estilos.COLOR_NEGRO_PURO);

        // --- 4. COMBOBOX ---
        Estilos.aplicarEstiloComboBox(jComboBoxInvoiceType);

        // --- 5. BOTONES E ICONOS ---
        Estilos.configurarBotonAccion(btnAccept);

        Estilos.configurarBotonAccion(btnCancel);

        Estilos.configurarBotonAccion(btnSearchClient);
        btnSearchClient.setText("");
        btnSearchClient.setIcon(crearIconoBlanco("img/search.svg", 20));
    }

    private FlatSVGIcon crearIconoBlanco(String ruta, int tamaño) {
        FlatSVGIcon icon = new FlatSVGIcon(ruta, tamaño, tamaño);
        icon.setColorFilter(new FlatSVGIcon.ColorFilter(c -> Estilos.COLOR_BLANCO));
        return icon;
    }
}
