/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.interfaz;

import com.formdev.flatlaf.extras.FlatSVGIcon;

/**
 *
 * @author poker
 */
public class DialogBuscarCliente extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogBuscarCliente.class.getName());

    // Variable para almacenar qué eligió el usuario
    private String clienteSeleccionado = null;

    /**
     * Creates new form DialogCrearFactura
     */
    public DialogBuscarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal ? java.awt.Dialog.ModalityType.APPLICATION_MODAL : java.awt.Dialog.ModalityType.MODELESS);
        initComponents();
        // 1. APLICAR ESTILOS VISUALES
        configurarEstilos();

        // 2. CONFIGURAR COLUMNAS DE LA TABLA
        configurarColumnas();

        // 3. AJUSTAR TAMAÑO Y POSICIÓN
        pack();
        setLocationRelativeTo(parent);

    }

    private void configurarColumnas() {
        // Nombre (150px)
        tblResultados.getColumnModel().getColumn(0).setPreferredWidth(150);
        // Apellido 1 (150px)
        tblResultados.getColumnModel().getColumn(1).setPreferredWidth(150);
        // Apellido 2 (150px)
        tblResultados.getColumnModel().getColumn(2).setPreferredWidth(150);
        // DNI (100px - más estrecho)
        tblResultados.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblResultados.getColumnModel().getColumn(3).setMaxWidth(120);
        // Nombre Comercial (El resto del espacio, min 250px)
        tblResultados.getColumnModel().getColumn(4).setPreferredWidth(250);

        // Altura de fila cómoda
        tblResultados.setRowHeight(30);
    }

    private void configurarEstilos() {
        // --- 1. FONDO PRINCIPAL ---
        panelPrincipal.setBackground(Estilos.COLOR_FONDO_MENTA);

        // --- 2. CAMPO DE BÚSQUEDA ---
        // Usamos el método específico para barras de búsqueda (redondo y blanco)
        Estilos.configurarBarraBusqueda(txtBuscar);
        txtBuscar.putClientProperty(com.formdev.flatlaf.FlatClientProperties.PLACEHOLDER_TEXT, "Buscar por nombre, DNI...");

        // --- 3. BOTONES DE ACCIÓN ---
        Estilos.configurarBotonAccion(btnBuscar);
        Estilos.configurarBotonAccion(btnAceptar);
        Estilos.configurarBotonAccion(btnCancelar);

        // Icono para el botón BUSCAR (Lupa blanca)
        // Asegúrate de tener "img/search_Icon.svg" o cambia la ruta
        FlatSVGIcon iconSearch = new FlatSVGIcon("img/search.svg", 18, 18);
        iconSearch.setColorFilter(new FlatSVGIcon.ColorFilter(c -> java.awt.Color.WHITE));
        btnBuscar.setIcon(iconSearch);
        btnBuscar.setText(""); // Quitamos texto para dejar solo icono (o déjalo si prefieres)

        // --- 4. TABLA ---
        // Aplicamos el estilo completo (Fondo menta, cabecera verde, selección negra)
        Estilos.configurarTabla(tblResultados, panelCentral);
    }

    // MÉTODO PÚBLICO PARA QUE EL PADRE LEA EL RESULTADO
    public String getClienteSeleccionado() {
        return clienteSeleccionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        panelBusqueda = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelCentral = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnCancelar = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnAceptar = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Factura");
        setModal(true);
        setResizable(false);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelBusqueda.setOpaque(false);
        panelBusqueda.setLayout(new java.awt.GridBagLayout());

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        panelBusqueda.add(txtBuscar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        panelBusqueda.add(btnBuscar, gridBagConstraints);

        panelPrincipal.add(panelBusqueda, java.awt.BorderLayout.PAGE_START);

        panelCentral.setMinimumSize(new java.awt.Dimension(800, 300));
        panelCentral.setPreferredSize(new java.awt.Dimension(800, 300));

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido 1", "Apellido 2", "DNI/NIE/CIF", "Nombre Comercial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panelCentral.setViewportView(tblResultados);

        panelPrincipal.add(panelCentral, java.awt.BorderLayout.CENTER);

        panelBotones.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        panelBotones.setOpaque(false);
        panelBotones.setLayout(new javax.swing.BoxLayout(panelBotones, javax.swing.BoxLayout.LINE_AXIS));
        panelBotones.add(filler4);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        panelBotones.add(btnCancelar);
        panelBotones.add(filler5);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);
        panelBotones.add(btnAceptar);
        panelBotones.add(filler3);

        panelPrincipal.add(panelBotones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // LÓGICA: Obtener el dato de la fila seleccionada
        int fila = tblResultados.getSelectedRow();
        if (fila != -1) {
            // Suponiendo que la columna 0 es el Nombre o lo que quieras devolver
            // Object valor = tblResultados.getValueAt(fila, 0);
            // clienteSeleccionado = valor.toString();

            // POR AHORA (Simulado):
            clienteSeleccionado = "Cliente Simulado S.L.";
            dispose(); // Cerrar ventana
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un cliente de la tabla");
        }    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        clienteSeleccionado = null; // No se eligió nada
        dispose();    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogBuscarCliente dialog = new DialogBuscarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JScrollPane panelCentral;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
