/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfaz;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author David CE
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        // --- DISEÑO MODERNIZADO CON FLATLAF --- 
        // Convertimos colores Hex a un objeto Color de Java una sola vez
        Color colorMenta = Color.decode("#CBF6E3");
        Color colorNegro = Color.BLACK;
        Color colorBlanco = Color.WHITE;

        // --- 1. USUARIO ---
        jTextFieldUser.putClientProperty(FlatClientProperties.STYLE, "arc: 999; focusedBorderColor: #CBF6E3; border: 1,1,1,1");
        jTextFieldUser.setBackground(colorNegro);
        jTextFieldUser.setForeground(colorBlanco);       // Letra blanca
        jTextFieldUser.setCaretColor(colorBlanco);       // Cursor blanco
        jTextFieldUser.setSelectionColor(colorMenta);    // Selección verde
        jTextFieldUser.setSelectedTextColor(colorNegro); // Texto seleccionado negro
        // Placeholder
        jTextFieldUser.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Introduzca su usuario");

        // --- 2. CONTRASEÑA ---
        jPasswordField.putClientProperty(FlatClientProperties.STYLE, "showRevealButton: true; arc: 999; focusedBorderColor: #CBF6E3; border: 1,1,1,1");

        jPasswordField.setBackground(colorNegro);
        jPasswordField.setForeground(colorBlanco);       // Al ser blanco, el ojo será blanco
        jPasswordField.setCaretColor(colorBlanco);
        jPasswordField.setSelectionColor(colorMenta);
        jPasswordField.setSelectedTextColor(colorNegro);
        // Placeholder
        jPasswordField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Introduzca su contraseña");

        // --- 3. BOTÓN ---
        jButtonEnter.putClientProperty(FlatClientProperties.STYLE, "arc: 999");
        jButtonEnter.setBackground(new Color(51, 51, 51));
        jButtonEnter.setForeground(Color.WHITE);
        jButtonEnter.setFocusPainted(false);

        // --- 4. ESTILO FUENTES ---
        // Etiquetas
        Font fuenteLabels = new Font("Century Gothic", Font.BOLD, 14);
        jLabelUser.setFont(fuenteLabels);
        jLabelPassword.setFont(fuenteLabels);

// Botón
        jButtonEnter.setFont(new Font("Century Gothic", Font.BOLD, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelLeft = new javax.swing.JPanel();
        jPanelCenter = new javax.swing.JPanel();
        jPanelContenido = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabelUser = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jButtonEnter = new javax.swing.JButton();
        jPanelRight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 360));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelLeft.setBackground(new java.awt.Color(160, 238, 204));

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelLeft, gridBagConstraints);

        jPanelCenter.setBackground(new java.awt.Color(160, 238, 204));
        jPanelCenter.setLayout(new java.awt.GridBagLayout());

        jPanelContenido.setBackground(new java.awt.Color(160, 238, 204));
        jPanelContenido.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        jPanelContenido.setLayout(new java.awt.GridBagLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/LOGO.png"))); // NOI18N
        jLabelLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanelContenido.add(jLabelLogo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanelContenido.add(filler1, gridBagConstraints);

        jLabelUser.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUser.setText("Usuario");
        jLabelUser.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanelContenido.add(jLabelUser, gridBagConstraints);

        jTextFieldUser.setMaximumSize(new java.awt.Dimension(300, 30));
        jTextFieldUser.setMinimumSize(new java.awt.Dimension(300, 30));
        jTextFieldUser.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanelContenido.add(jTextFieldUser, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanelContenido.add(filler2, gridBagConstraints);

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPassword.setText("Contraseña");
        jLabelPassword.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanelContenido.add(jLabelPassword, gridBagConstraints);

        jPasswordField.setMaximumSize(new java.awt.Dimension(300, 30));
        jPasswordField.setMinimumSize(new java.awt.Dimension(300, 30));
        jPasswordField.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanelContenido.add(jPasswordField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanelContenido.add(filler3, gridBagConstraints);

        jButtonEnter.setText("Entrar");
        jButtonEnter.setAlignmentX(0.5F);
        jButtonEnter.setPreferredSize(new java.awt.Dimension(100, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanelContenido.add(jButtonEnter, gridBagConstraints);

        jPanelCenter.add(jPanelContenido, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelCenter, gridBagConstraints);

        jPanelRight.setBackground(new java.awt.Color(160, 238, 204));

        javax.swing.GroupLayout jPanelRightLayout = new javax.swing.GroupLayout(jPanelRight);
        jPanelRight.setLayout(jPanelRightLayout);
        jPanelRightLayout.setHorizontalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        jPanelRightLayout.setVerticalGroup(
            jPanelRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanelRight, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
