/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.interfaz;

/**
 *
 * @author DavidCe
 */
public class PanelProductos extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelProductos() {
        initComponents();

        // --- 1. TABLA
        // --- APLICAR ESTILO A LA TABLA ---
        Estilos.configurarTabla(tblProducts, jScrollPaneCenter);

        // --- DEFINIR ANCHOS DE COLUMNAS ---
        // Código Producto: 90px (Tamaño ideal para números de 4-5 cifras)
        tblProducts.getColumnModel().getColumn(0).setPreferredWidth(90);
        tblProducts.getColumnModel().getColumn(0).setMaxWidth(110);

        // Descripción: 250px
        tblProducts.getColumnModel().getColumn(1).setPreferredWidth(450);

        // Precio: 90px 
        tblProducts.getColumnModel().getColumn(2).setPreferredWidth(50);

        // Tipo IVA: 90 px
        tblProducts.getColumnModel().getColumn(3).setPreferredWidth(50);

        // Bloquear reordenamiento
        tblProducts.getTableHeader().setReorderingAllowed(false);

        // --- 2. BARRA DE BÚSQUEDA
        // --- APLICAR ESTILO A LA BARRA DE BÚSQUEDA ---
        Estilos.configurarBarraBusqueda(txtSearch);
        txtSearch.putClientProperty(com.formdev.flatlaf.FlatClientProperties.PLACEHOLDER_TEXT, "Buscar Producto por Descripción o Código");

        // --- 3. BOTONES
        // --- APLICAR ESTILO A LOS BOTONES ---
        // Creamos una lista con todos los botones para aplicarles el estilo "Píldora Negra" de golpe
        javax.swing.JButton[] botonesAccion = {
            btnAddProduct, // Añadir Cliente
            btnEditProduct, // Editar
            btnDeleteProduct // Borrar
        };

        for (javax.swing.JButton btn : botonesAccion) {
            Estilos.configurarBotonAccion(btn);
        }

        // Botón Home como Icono
        com.formdev.flatlaf.extras.FlatSVGIcon homeIcon = new com.formdev.flatlaf.extras.FlatSVGIcon("img/home_Icon.svg", 32, 32);
        // Usamos Color.BLACK (o Color.decode("#111111") para negro suave)
        homeIcon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.BLACK));
        btnHome.setIcon(homeIcon);
        btnHome.setText("");
        // Estilo "invisible" para que solo se vea el icono
        btnHome.setContentAreaFilled(false);
        btnHome.setBorderPainted(false);
        btnHome.setFocusPainted(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Añadir icono a los botones
        setIconoBlanco(btnEditProduct, "img/edit_icon.svg");
        setIconoBlanco(btnDeleteProduct, "img/delete_icon.svg");

        // --- CONFIGURACIÓN BOTÓN AÑADIR PRODUCTO ---
        // 1. Cargar el icono SVG (Tamaño 20x20)
        com.formdev.flatlaf.extras.FlatSVGIcon iconAdd = new com.formdev.flatlaf.extras.FlatSVGIcon("img/add_Icon.svg", 20, 20);

        // 2. Pintarlo de BLANCO (porque el botón es negro)
        iconAdd.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(c -> java.awt.Color.WHITE));

        // 3. Asignarlo al botón
        btnAddProduct.setIcon(iconAdd);

        // 4. Ajustes visuales
        btnAddProduct.setIconTextGap(10); // Espacio entre el (+) y el texto
        btnAddProduct.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Texto a la derecha del icono

        // Asegurarnos de que el texto esté centrado verticalmente
        btnAddProduct.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        // Ajustes finales de texto y márgenes
        javax.swing.JButton[] botones = {btnEditProduct, btnDeleteProduct};
        for (javax.swing.JButton btn : botones) {
            btn.setIconTextGap(15);
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            // Ajusta este margen si quieres los botones más o menos anchos
            btn.setMargin(new java.awt.Insets(10, 15, 10, 15));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCenter = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnAddProduct = new javax.swing.JButton();
        jScrollPaneCenter = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jPanelRight = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnEditProduct = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        btnDeleteProduct = new javax.swing.JButton();

        setBackground(new java.awt.Color(160, 238, 204));
        setLayout(new java.awt.BorderLayout());

        jPanelCenter.setBackground(new java.awt.Color(160, 238, 204));
        jPanelCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelCenter.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 10);
        jPanelCenter.add(txtSearch, gridBagConstraints);

        btnAddProduct.setText("Añadir Producto");
        btnAddProduct.addActionListener(this::btnAddProductActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 15, 10);
        jPanelCenter.add(btnAddProduct, gridBagConstraints);

        jScrollPaneCenter.setOpaque(false);

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Descripción", "Precio", "Tipo IVA"
            }
        ));
        jScrollPaneCenter.setViewportView(tblProducts);
        if (tblProducts.getColumnModel().getColumnCount() > 0) {
            tblProducts.getColumnModel().getColumn(0).setResizable(false);
            tblProducts.getColumnModel().getColumn(1).setResizable(false);
            tblProducts.getColumnModel().getColumn(2).setResizable(false);
            tblProducts.getColumnModel().getColumn(3).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelCenter.add(jScrollPaneCenter, gridBagConstraints);

        add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelRight.setOpaque(false);
        jPanelRight.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelRight.setLayout(new java.awt.GridBagLayout());

        btnHome.setText("HOME");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnHome, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler1, gridBagConstraints);

        btnEditProduct.setText("Editar Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnEditProduct, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler2, gridBagConstraints);

        btnDeleteProduct.setText("Borrar Producto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelRight.add(btnDeleteProduct, gridBagConstraints);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // 1. Instanciar el formulario de productos (NO clientes)
        PanelCrearProducto pnlCrear = new PanelCrearProducto();

        // 2. Obtener el contenedor padre
        javax.swing.JPanel parent = (javax.swing.JPanel) getParent();

        // (Opcional) Capturar listeners del botón Home si usas esa lógica
        // java.awt.event.ActionListener[] listenersHome = btnHome.getActionListeners();
        // 3. Configurar el botón "VOLVER"
        pnlCrear.getBtnBack().addActionListener(e -> {
            parent.removeAll();

            // --- AQUÍ ESTÁ EL CAMBIO ---
            // Antes tenías: parent.add(new PanelClientes(), ...);
            // Cámbialo por:
            parent.add(new PanelProductos(), java.awt.BorderLayout.CENTER);

            // (Opcional) Restaurar listeners del Home...
            parent.revalidate();
            parent.repaint();
        });

        // 4. Mostrar el formulario
        parent.removeAll();
        parent.add(pnlCrear, java.awt.BorderLayout.CENTER);
        parent.revalidate();
        parent.repaint();    }//GEN-LAST:event_btnAddProductActionPerformed

    private void setIconoBlanco(javax.swing.JButton btn, String rutaSvg) {
        com.formdev.flatlaf.extras.FlatSVGIcon icon = new com.formdev.flatlaf.extras.FlatSVGIcon(rutaSvg, 20, 20);
        // ESTO ES LA MAGIA: Fuerza el color blanco
        icon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.WHITE));
        btn.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnHome;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JScrollPane jScrollPaneCenter;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    // Método puente para acceder al botón Home desde fuera
    public javax.swing.JButton getBtnHome() {
        return btnHome;
    }
}
