/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.interfaz;

/**
 *
 * @author DavidCe
 */
public class PanelCrearProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelCrearProducto() {
        initComponents();
        // --- 1. APLICAR ESTILO A LOS CAMPOS DE TEXTO (CAMBIO: Usamos el nuevo estilo Formulario) ---
        javax.swing.JTextField[] campos = {
            txtDescription, txtProductCode, txtUnitAmount
        };

        for (javax.swing.JTextField t : campos) {
            Estilos.configurarCampoFormulario(t);
        }

        // --- APLICAR ESTILO A LOS COMBOBOX ---
        javax.swing.JComboBox[] combos = {jComboBoxTaxType, jComboBoxTaxRate};
        for (javax.swing.JComboBox c : combos) {
            Estilos.aplicarEstiloComboBox(c);

            // --- TRUCO FINAL DE ALINEACIÓN ---
            // Forzamos a que el ComboBox tenga la misma altura preferida que el TextField de al lado.
            // (Asumimos que txtUnitAmount ya tiene su estilo aplicado)
            java.awt.Dimension sizeRef = txtUnitAmount.getPreferredSize();

            // Le damos el ancho que quiera el combo, pero la ALTURA del textfield
            c.setPreferredSize(new java.awt.Dimension(c.getPreferredSize().width, sizeRef.height));
            c.setMinimumSize(new java.awt.Dimension(c.getMinimumSize().width, sizeRef.height));
        }

        // --- 2. APLICAR ESTILO A LAS ETIQUETAS (LABELS) ---
        // Esto hará que los textos "Nombre", "Dirección", etc. se vean GRANDES
        javax.swing.JLabel[] etiquetas = {
            lblDescription, lblTaxType, lblProductCode, lblTaxRate, lblUnitAmount
        };

        for (javax.swing.JLabel l : etiquetas) {
            Estilos.configurarEtiquetaFormulario(l);
        }

        // --- 3. BOTONES DE ACCIÓN ---
        setIconoBlanco(btnAddClient, "img/add_Icon.svg");
        setIconoBlanco(btnBack, "img/delete_Icon.svg");
        javax.swing.JButton[] botonesAccion = {btnAddClient, btnBack};

        for (javax.swing.JButton btn : botonesAccion) {
            Estilos.configurarBotonAccion(btn);
            // --- CORRECCIÓN DE ALINEACIÓN ---
            btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); // Texto Centrado
            btn.setIconTextGap(15); // Espacio entre icono y texto
            btn.setMargin(new java.awt.Insets(10, 20, 10, 20)); // Más gorditos
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCenter = new javax.swing.JPanel();
        jPanelForm = new javax.swing.JPanel();
        lblProductCode = new javax.swing.JLabel();
        txtProductCode = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblUnitAmount = new javax.swing.JLabel();
        txtUnitAmount = new javax.swing.JTextField();
        lblTaxType = new javax.swing.JLabel();
        jComboBoxTaxType = new javax.swing.JComboBox<>();
        lblTaxRate = new javax.swing.JLabel();
        jComboBoxTaxRate = new javax.swing.JComboBox<>();
        jPanelButtons = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        btnAddClient = new javax.swing.JButton();
        jPanelRight = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setBackground(new java.awt.Color(160, 238, 204));
        setLayout(new java.awt.BorderLayout());

        jPanelCenter.setBackground(new java.awt.Color(160, 238, 204));
        jPanelCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelCenter.setLayout(new java.awt.GridBagLayout());

        jPanelForm.setBackground(new java.awt.Color(203, 246, 227));
        jPanelForm.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(0, 80, 0, 80)));
        jPanelForm.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanelForm.setLayout(new java.awt.GridBagLayout());

        lblProductCode.setText("Código");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 10, 500);
        jPanelForm.add(lblProductCode, gridBagConstraints);

        txtProductCode.addActionListener(this::txtProductCodeActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 500);
        jPanelForm.add(txtProductCode, gridBagConstraints);

        lblDescription.setText("Descripción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 10, 10);
        jPanelForm.add(lblDescription, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPanelForm.add(txtDescription, gridBagConstraints);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblUnitAmount.setText("Precio Ud.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 10, 500);
        jPanel1.add(lblUnitAmount, gridBagConstraints);

        txtUnitAmount.addActionListener(this::txtUnitAmountActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 500);
        jPanel1.add(txtUnitAmount, gridBagConstraints);

        lblTaxType.setText("Régimen IVA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, -448, 10, 200);
        jPanel1.add(lblTaxType, gridBagConstraints);

        jComboBoxTaxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -450, 0, 200);
        jPanel1.add(jComboBoxTaxType, gridBagConstraints);

        lblTaxRate.setText("% IVA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, -148, 10, 0);
        jPanel1.add(lblTaxRate, gridBagConstraints);

        jComboBoxTaxRate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, -150, 0, 0);
        jPanel1.add(jComboBoxTaxRate, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelForm.add(jPanel1, gridBagConstraints);

        jPanelButtons.setOpaque(false);

        btnBack.setText("Volver");
        btnBack.addActionListener(this::btnBackActionPerformed);
        jPanelButtons.add(btnBack);

        filler3.setAlignmentX(1.0F);
        filler3.setAlignmentY(1.0F);
        jPanelButtons.add(filler3);

        btnAddClient.setText("Agregar");
        jPanelButtons.add(btnAddClient);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanelForm.add(jPanelButtons, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(80, 40, 80, 40);
        jPanelCenter.add(jPanelForm, gridBagConstraints);

        add(jPanelCenter, java.awt.BorderLayout.CENTER);
        jPanelCenter.getAccessibleContext().setAccessibleParent(jPanelCenter);

        jPanelRight.setOpaque(false);
        jPanelRight.setPreferredSize(new java.awt.Dimension(200, 0));
        jPanelRight.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weighty = 1.0;
        jPanelRight.add(filler2, gridBagConstraints);

        add(jPanelRight, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnitAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitAmountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtProductCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductCodeActionPerformed

    private void setIconoBlanco(javax.swing.JButton btn, String rutaSvg) {
        com.formdev.flatlaf.extras.FlatSVGIcon icon = new com.formdev.flatlaf.extras.FlatSVGIcon(rutaSvg, 20, 20);
        // ESTO ES LA MAGIA: Fuerza el color blanco
        icon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(color -> java.awt.Color.WHITE));
        btn.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClient;
    private javax.swing.JButton btnBack;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JComboBox<String> jComboBoxTaxRate;
    private javax.swing.JComboBox<String> jComboBoxTaxType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblProductCode;
    private javax.swing.JLabel lblTaxRate;
    private javax.swing.JLabel lblTaxType;
    private javax.swing.JLabel lblUnitAmount;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtProductCode;
    private javax.swing.JTextField txtUnitAmount;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnBack() {
        return btnBack;
    }

    public javax.swing.JButton getBtnAddClient() { // El botón "Agregar" del formulario
        return btnAddClient;
    }
}
